services:
  config_debug:
    class: Drupal\Console\Command\Config\DebugCommand
    arguments: ['@config.factory', '@config.storage']
    tags:
      - { name: console.command }
  config_delete:
    class: Drupal\Console\Command\Config\DeleteCommand
    arguments: ['@config.factory', '@config.storage', '@config.storage.sync']
    tags:
      - { name: console.command }
  config_diff:
    class: Drupal\Console\Command\Config\DiffCommand
    arguments: ['@config.storage', '@config.manager']
    tags:
      - { name: console.command }
  config_edit:
    class: Drupal\Console\Command\Config\EditCommand
    arguments: ['@config.factory', '@config.storage', '@console.configuration_manager']
    tags:
      - { name: console.command }
  config_export:
    class: Drupal\Console\Command\Config\ExportCommand
    arguments: ['@config.manager']
    tags:
      - { name: console.command }
#  config_export_content_type:
#    class: Drupal\Console\Command\Config\ExportContentTypeCommand
#    tags:
#      - { name: console.command }
#  config_export_view:
#    class: Drupal\Console\Command\Config\ExportViewCommand
#    tags:
#      - { name: console.command }
#  config_import:
#    class: Drupal\Console\Command\Config\ImportCommand
#    tags:
#      - { name: console.command }
#  config_import_single:
#    class: Drupal\Console\Command\Config\ImportSingleCommand
#    tags:
#      - { name: console.command }
#  config_override:
#    class: Drupal\Console\Command\Config\OverrideCommand
#    tags:
#      - { name: console.command }
#  config_settings_debug:
#    class: Drupal\Console\Command\Config\SettingsDebugCommand
#    tags:
#      - { name: console.command }
