services:
  console.database_client:
    class: Drupal\Console\Command\Database\ClientCommand
    tags:
      - { name: drupal.command }
  console.database_drop:
    class: Drupal\Console\Command\Database\DropCommand
    tags:
      - { name: drupal.command }
  console.database_dump:
    class: Drupal\Console\Command\Database\DumpCommand
    arguments: ['@app.root', '@console.shell_process', '@database']
    tags:
      - { name: drupal.command }
  console.database_log_clear:
    class: Drupal\Console\Command\Database\LogClearCommand
    arguments: ['@database']
    tags:
      - { name: drupal.command }
  console.database_log_poll:
    class: Drupal\Console\Command\Database\LogPollCommand
    arguments: ['@database', '@date.formatter', '@entity_type.manager', '@string_translation']
    tags:
      - { name: drupal.command }
