services:
  console.generate_module:
    class: Drupal\Console\Command\Generate\ModuleCommand
    arguments: ['@console.module_generator', '@console.validator', '@app.root', '@console.string_converter', '@console.drupal_api']
    tags:
       - { name: drupal.command }
  console.generate_modulefile:
    class: Drupal\Console\Command\Generate\ModuleFileCommand
    arguments: ['@console.extension_manager', '@console.modulefile_generator']
    tags:
       - { name: drupal.command }
  console.generate_authentication_provider:
    class: Drupal\Console\Command\Generate\AuthenticationProviderCommand
    arguments: ['@console.extension_manager', '@console.authentication_provider_generator', '@console.string_converter']
    tags:
       - { name: drupal.command }
  console.generate_controller:
    class: Drupal\Console\Command\Generate\ControllerCommand
    arguments: ['@console.extension_manager', '@console.controller_generator', '@console.string_converter', '@console.validator', '@router.route_provider', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_breakpoint:
    class: Drupal\Console\Command\Generate\BreakPointCommand
    arguments: ['@console.breakpoint_generator', '@app.root', '@theme_handler', '@console.validator', '@console.string_converter']
    tags:
      - { name: drupal.command }
  console.generate_help:
    class: Drupal\Console\Command\Generate\HelpCommand
    arguments: ['@console.help_generator', '@console.site', '@console.extension_manager', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_form:
    class: Drupal\Console\Command\Generate\FormBaseCommand
    arguments: ['@console.extension_manager', '@console.form_generator', '@console.chain_queue', '@console.string_converter', '@plugin.manager.element_info', '@router.route_provider']
    tags:
       - { name: drupal.command }
  console.generate_form_alter:
    class: Drupal\Console\Command\Generate\FormAlterCommand
    arguments: ['@console.extension_manager', '@console.form_alter_generator', '@console.string_converter', '@module_handler', '@plugin.manager.element_info', '@?profiler', '@app.root', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_permissions:
    class: Drupal\Console\Command\Generate\PermissionCommand
    arguments: ['@console.extension_manager', '@console.string_converter', '@console.permission_generator']
    tags:
       - { name: drupal.command }
  console.generate_event_subscriber:
    class: Drupal\Console\Command\Generate\EventSubscriberCommand
    arguments: ['@console.extension_manager', '@console.event_subscriber_generator', '@console.string_converter', '@event_dispatcher', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_form_config:
    class: Drupal\Console\Command\Generate\ConfigFormBaseCommand
    arguments: ['@console.extension_manager', '@console.form_generator', '@console.string_converter', '@router.route_provider', '@plugin.manager.element_info', '@app.root', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_type_annotation:
    class: Drupal\Console\Command\Generate\PluginTypeAnnotationCommand
    arguments: ['@console.extension_manager', '@console.plugin_type_annotation_generator', '@console.string_converter']
    tags:
       - { name: drupal.command }
  console.generate_plugin_condition:
    class: Drupal\Console\Command\Generate\PluginConditionCommand
    arguments: ['@console.extension_manager', '@console.plugin_condition_generator', '@console.chain_queue', '@entity_type.repository', '@console.string_converter']
    tags:
       - { name: drupal.command }
  console.generate_plugin_field:
    class: Drupal\Console\Command\Generate\PluginFieldCommand
    arguments: ['@console.extension_manager','@console.string_converter', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_field_formatter:
    class: Drupal\Console\Command\Generate\PluginFieldFormatterCommand
    arguments: ['@console.extension_manager', '@console.plugin_field_formatter_generator','@console.string_converter', '@plugin.manager.field.field_type', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_field_type:
    class: Drupal\Console\Command\Generate\PluginFieldTypeCommand
    arguments: ['@console.extension_manager', '@console.plugin_field_type_generator','@console.string_converter', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_field_widget:
    class: Drupal\Console\Command\Generate\PluginFieldWidgetCommand
    arguments: ['@console.extension_manager', '@console.plugin_field_widget_generator','@console.string_converter', '@plugin.manager.field.field_type', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_image_effect:
    class: Drupal\Console\Command\Generate\PluginImageEffectCommand
    arguments: ['@console.extension_manager', '@console.plugin_image_effect_generator','@console.string_converter', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_image_formatter:
    class: Drupal\Console\Command\Generate\PluginImageFormatterCommand
    arguments: ['@console.extension_manager', '@console.plugin_image_formatter_generator','@console.string_converter', '@console.validator', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_mail:
    class: Drupal\Console\Command\Generate\PluginMailCommand
    arguments: ['@console.extension_manager', '@console.plugin_mail_generator','@console.string_converter', '@console.validator', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_migrate_source:
    class: Drupal\Console\Command\Generate\PluginMigrateSourceCommand
    arguments: ['@config.factory', '@console.chain_queue', '@console.plugin_migrate_source_generator', '@entity_type.manager', '@console.extension_manager', '@console.validator', '@console.string_converter', '@plugin.manager.element_info']
    tags:
       - { name: drupal.command }
  console.generate_plugin_migrate_process:
    class: Drupal\Console\Command\Generate\PluginMigrateProcessCommand
    arguments: [ '@console.plugin_migrate_process_generator', '@console.chain_queue', '@console.extension_manager', '@console.string_converter']
    tags:
       - { name: drupal.command }
  console.generate_plugin_rest_resource:
    class: Drupal\Console\Command\Generate\PluginRestResourceCommand
    arguments: ['@console.extension_manager', '@console.plugin_rest_resource_generator','@console.string_converter', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_rules_action:
    class: Drupal\Console\Command\Generate\PluginRulesActionCommand
    arguments: ['@console.extension_manager', '@console.plugin_rules_action_generator','@console.string_converter', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_skeleton:
    class: Drupal\Console\Command\Generate\PluginSkeletonCommand
    arguments: ['@console.extension_manager', '@console.plugin_skeleton_generator','@console.string_converter', '@console.validator', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_plugin_type_yaml:
    class: Drupal\Console\Command\Generate\PluginTypeYamlCommand
    arguments: ['@console.extension_manager', '@console.plugin_type_yaml_generator','@console.string_converter']
    tags:
       - { name: drupal.command }
  console.generate_plugin_views_field:
    class: Drupal\Console\Command\Generate\PluginViewsFieldCommand
    arguments: ['@console.extension_manager', '@console.plugin_views_field_generator', '@console.site','@console.string_converter','@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_post_update:
    class: Drupal\Console\Command\Generate\PostUpdateCommand
    arguments: ['@console.extension_manager', '@console.post_update_generator', '@console.site', '@console.validator','@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_profile:
    class: Drupal\Console\Command\Generate\ProfileCommand
    arguments: ['@console.extension_manager', '@console.profile_generator', '@console.string_converter', '@console.validator', '@app.root']
    tags:
       - { name: drupal.command }
  console.generate_route_subscriber:
    class: Drupal\Console\Command\Generate\RouteSubscriberCommand
    arguments: ['@console.extension_manager', '@console.route_subscriber_generator', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_service:
    class: Drupal\Console\Command\Generate\ServiceCommand
    arguments: ['@console.extension_manager', '@console.service_generator', '@console.string_converter', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_theme:
    class: Drupal\Console\Command\Generate\ThemeCommand
    arguments: ['@console.extension_manager', '@console.theme_generator', '@console.validator', '@app.root', '@theme_handler', '@console.site', '@console.string_converter']
    tags:
       - { name: drupal.command }
  console.generate_twig_extension:
    class: Drupal\Console\Command\Generate\TwigExtensionCommand
    arguments: ['@console.extension_manager', '@console.twig_extension_generator', '@console.site', '@console.string_converter', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_update:
    class: Drupal\Console\Command\Generate\UpdateCommand
    arguments: ['@console.extension_manager', '@console.update_generator', '@console.site', '@console.chain_queue']
    tags:
       - { name: drupal.command }
  console.generate_pluginblock:
    class: Drupal\Console\Command\Generate\PluginBlockCommand
    arguments: ['@config.factory', '@console.chain_queue', '@console.pluginblock_generator', '@entity_type.manager', '@console.extension_manager', '@console.validator', '@console.string_converter', '@plugin.manager.element_info']
    tags:
       - { name: drupal.command }
  console.generate_command:
    class: Drupal\Console\Command\Generate\CommandCommand
    arguments: ['@console.command_generator', '@console.extension_manager', '@console.validator', '@console.string_converter', '@console.site']
    tags:
       - { name: drupal.command }
  console.generate_ckeditorbutton:
    class: Drupal\Console\Command\Generate\PluginCKEditorButtonCommand
    arguments: ['@console.chain_queue', '@console.command_ckeditorbutton', '@console.extension_manager', '@console.string_converter']
    tags:
       - { name: drupal.command }
  console.generate_entitycontent:
    class: Drupal\Console\Command\Generate\EntityContentCommand
    arguments: ['@console.chain_queue', '@console.entitycontent_generator', '@console.string_converter', '@console.extension_manager', '@console.validator']
    tags:
       - { name: drupal.command }
  console.generate_entitybundle:
    class: Drupal\Console\Command\Generate\EntityBundleCommand
    arguments: ['@console.validator', '@console.entitybundle_generator', '@console.extension_manager']
    tags:
       - { name: drupal.command }
  console.generate_entityconfig:
    class: Drupal\Console\Command\Generate\EntityConfigCommand
    arguments: ['@console.extension_manager', '@console.entityconfig_generator', '@console.validator', '@console.string_converter']
    tags:
       - { name: drupal.command }
  console.generate_cache_context:
    class: Drupal\Console\Command\Generate\CacheContextCommand
    arguments: [ '@console.cache_context_generator', '@console.chain_queue', '@console.extension_manager', '@console.string_converter']
    tags:
       - { name: drupal.command }
