services:
  translation_status:
    class: Drupal\Console\Command\Locale\TranslationStatusCommand
    arguments: ['@console.drupal_api']
    tags:
      - { name: console.command }
  language_delete:
    class: Drupal\Console\Command\Locale\LanguageDeleteCommand
    arguments: ['@entity_type.manager']
    tags:
      - { name: console.command }
  language_add:
    class: Drupal\Console\Command\Locale\LanguageAddCommand
    arguments: ['@module_handler', '@console.drupal_api']
    tags:
      - { name: console.command }
