services:
  console.role_new:
    class: Drupal\Console\Command\Role\NewCommand
    arguments: ['@database', '@entity_type.manager', '@date.formatter', '@console.drupal_api', '@console.validator', '@console.string_converter']
    tags:
      - { name: drupal.command }
  console.role_delete:
    class: Drupal\Console\Command\Role\DeleteCommand
    arguments: ['@database', '@entity_type.manager', '@date.formatter', '@console.drupal_api']
    tags:
      - { name: drupal.command }