services:
  theme_debug:
    class: Drupal\Console\Command\Theme\DebugCommand
    arguments: ['@config.factory', '@theme_handler']
    tags:
      - { name: console.command }
  theme_download:
    class: Drupal\Console\Command\Theme\DownloadCommand
    arguments: ['@console.drupal_api', '@http_client', '@app.root']
    tags:
      - { name: console.command }
  theme_install:
    class: Drupal\Console\Command\Theme\InstallCommand
    arguments: ['@config.factory', '@theme_handler']
    tags:
      - { name: console.command }
  theme_path:
    class: Drupal\Console\Command\Theme\PathCommand
    arguments: ['@console.extension_manager']
    tags:
      - { name: console.command }
  theme_uninstall:
    class: Drupal\Console\Command\Theme\UninstallCommand
    arguments: ['@config.factory', '@theme_handler']
    tags:
      - { name: console.command }
