application:
  autowire:
    commands:
      forced:
        _completion:
          class: '\Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand'
          helperset: false
      name:
        elephpant:
          class: '\Drupal\Console\Command\Exclude\ElephpantCommand'
          helperset: true
        druplicon:
          class: '\Drupal\Console\Command\Exclude\DrupliconCommand'
          helperset: true
  languages:
      en: 'English'
      es: 'Español'
      ca: 'Català'
      fr: 'Français'
      hi: 'हिन्दी'
      hu: 'Magyar'
      ja: '日本語'
      pt_br: 'Português (br)'
      ro: 'Romanian'
      ru: 'pусский язык'
      vn: 'Tiếng Việt'
      zh_hans: '简体中文'
      mr: 'मराठी'
