services:
#  redbean:
#    class: RedBeanPHP\R
  console.annotation_reader:
    class: Doctrine\Common\Annotations\AnnotationReader
  console.annotation_file_cache:
    class: Doctrine\Common\Annotations\FileCacheReader
    factory: [Drupal\Console\Annotations\CacheFactory, createFileCache]
    arguments: ['@console.annotation_reader', '@console.configuration_manager']
#  console.command_dependencies:
#    class: Drupal\Console\Command\CommandDependencies
#    arguments: ["@console.annotation_file_cache"]
  console.validator:
    class: Drupal\Console\Utils\Validator
  console.drupal_api:
    class: Drupal\Console\Utils\DrupalApi
    arguments: ['@app.root', '@entity_type.manager']
  console.create_node_data:
    class: Drupal\Console\Utils\Create\NodeData
    arguments: ['@entity_type.manager', '@entity_field.manager', '@date.formatter', '@=service("console.drupal_api").getBundles()']
  console.create_comment_data:
    class: Drupal\Console\Utils\Create\CommentData
    arguments: ['@entity_type.manager', '@entity_field.manager', '@date.formatter']
  console.create_term_data:
    class: Drupal\Console\Utils\Create\TermData
    arguments: ['@entity_type.manager', '@entity_field.manager', '@date.formatter', '@=service("console.drupal_api").getVocabularies()']
  console.create_user_data:
    class: Drupal\Console\Utils\Create\UserData
    arguments: ['@entity_type.manager', '@entity_field.manager', '@date.formatter', '@=service("console.drupal_api").getRoles()']
