services:
  parser:
    class: Symfony\Component\Yaml\Parser
  filesystem:
    class: Symfony\Component\Filesystem\Filesystem
  yaml:
    class: Symfony\Component\Yaml\Yaml
  config:
    class: Drupal\Console\Config
    arguments: ["@parser"]
  requirement_checker:
    class: Drupal\Console\Utils\RequirementChecker
    arguments: ["@parser"]
  redbean:
    class: RedBeanPHP\R
  annotation_reader:
    class: Doctrine\Common\Annotations\AnnotationReader
  annotation_file_cache:
    class: Doctrine\Common\Annotations\FileCacheReader
    factory: [Drupal\Console\Annotations\CacheFactory, createFileCache]
    arguments: ['@annotation_reader', '@config']
  command_dependency_resolver:
    class: Drupal\Console\Command\CommandDependencies
    arguments: ["@annotation_file_cache"]
  file_util:
    class: Drupal\Console\Utils\File
  translator:
    class: Drupal\Console\Utils\Translator
    arguments: ["@parser", "@filesystem"]
  site:
    class: Drupal\Console\Utils\Site
    arguments: ["@parser"]
  chain_queue:
    class: Drupal\Console\Utils\ChainQueue
  showfile:
    class: Drupal\Console\Utils\ShowFile
    arguments: ["@site", "@translator"]
  shell_process:
    class: Drupal\Console\Utils\ShellProcess
    arguments: ["@site"]
  about:
    class: Drupal\Console\Command\AboutCommand
    tags:
      - { name: console.command }
  check:
    class: Drupal\Console\Command\CheckCommand
    tags:
      - { name: console.command }
  complete:
    class: Drupal\Console\Command\CompleteCommand
    tags:
      - { name: console.command }
  init:
    class: Drupal\Console\Command\InitCommand
    tags:
      - { name: console.command }
  list:
    class: Drupal\Console\Command\ListCommand
    tags:
      - { name: console.command }
  help:
    class: Drupal\Console\Command\HelpCommand
    tags:
      - { name: console.command }
  server:
    class: Drupal\Console\Command\ServerCommand
    tags:
      - { name: console.command }
  cache_rebuild:
    class: Drupal\Console\Command\CacheRebuildCommand
    tags:
      - { name: console.command }
  cache_rebuild:
    class: Drupal\Console\Command\CacheRebuildCommand
    tags:
      - { name: console.command }
  plugin_debug:
      class: Drupal\Console\Command\PluginDebugCommand
      tags:
        - { name: console.command }
  container_debug:
      class: Drupal\Console\Command\ContainerDebugCommand
      tags:
        - { name: console.command }
  breakpoints_debug:
      class: Drupal\Console\Command\Breakpoints\DebugCommand
      tags:
        - { name: console.command }
  views_plugins_debug:
      class: Drupal\Console\Command\Views\PluginsDebugCommand
      tags:
        - { name: console.command }
  views_enable:
      class: Drupal\Console\Command\Views\EnableCommand
      tags:
        - { name: console.command }
  views_disable:
      class: Drupal\Console\Command\Views\DisableCommand
      tags:
        - { name: console.command }
  views_debug:
      class: Drupal\Console\Command\Views\DebugCommand
      tags:
        - { name: console.command }
  chain:
      class: Drupal\Console\Command\Chain\ChainCommand
      tags:
        - { name: console.command }
  chain_debug:
      class: Drupal\Console\Command\Chain\ChainDebugCommand
      tags:
        - { name: console.command }
  config_debug:
      class: Drupal\Console\Command\Config\DebugCommand
      tags:
        - { name: console.command }
  config_delete:
      class: Drupal\Console\Command\Config\DeleteCommand
      tags:
        - { name: console.command }
  config_diff:
      class: Drupal\Console\Command\Config\DiffCommand
      tags:
        - { name: console.command }
  config_edit:
      class: Drupal\Console\Command\Config\EditCommand
      tags:
        - { name: console.command }
  config_export:
      class: Drupal\Console\Command\Config\ExportCommand
      tags:
        - { name: console.command }
  config_export_content_type:
      class: Drupal\Console\Command\Config\ExportContentTypeCommand
      tags:
        - { name: console.command }
  config_export_view:
      class: Drupal\Console\Command\Config\ExportViewCommand
      tags:
        - { name: console.command }
  config_import:
      class: Drupal\Console\Command\Config\ImportCommand
      tags:
        - { name: console.command }
  config_import_single:
      class: Drupal\Console\Command\Config\ImportSingleCommand
      tags:
        - { name: console.command }
  config_override:
      class: Drupal\Console\Command\Config\OverrideCommand
      tags:
        - { name: console.command }
  config_settings_debug:
      class: Drupal\Console\Command\Config\SettingsDebugCommand
      tags:
        - { name: console.command }
  cron_debug:
      class: Drupal\Console\Command\Cron\DebugCommand
      tags:
        - { name: console.command }
  cron_execute:
      class: Drupal\Console\Command\Cron\ExecuteCommand
      tags:
        - { name: console.command }
  cron_release:
      class: Drupal\Console\Command\Cron\ReleaseCommand
      tags:
        - { name: console.command }
  site_install:
      class: Drupal\Console\Command\Site\InstallCommand
      tags:
        - { name: console.command }
  database_client:
      class: Drupal\Console\Command\Database\ClientCommand
      tags:
        - { name: console.command }
  database_connect:
      class: Drupal\Console\Command\Database\ConnectCommand
      tags:
        - { name: console.command }
  database_drop:
      class: Drupal\Console\Command\Database\DropCommand
      tags:
        - { name: console.command }
  database_dump:
      class: Drupal\Console\Command\Database\DumpCommand
      tags:
        - { name: console.command }
  database_log_clear:
      class: Drupal\Console\Command\Database\LogClearCommand
      tags:
        - { name: console.command }
  database_log_debug:
        class: Drupal\Console\Command\Database\LogDebugCommand
        tags:
          - { name: console.command }
  database_restore:
        class: Drupal\Console\Command\Database\RestoreCommand
        tags:
          - { name: console.command }
  database_table_debug:
        class: Drupal\Console\Command\Database\TableDebugCommand
        tags:
          - { name: console.command }
  image_styles_debug:
        class: Drupal\Console\Command\Image\StylesDebugCommand
        tags:
          - { name: console.command }
  image_styles_flush:
        class: Drupal\Console\Command\Image\StylesFlushCommand
        tags:
          - { name: console.command }
  libraries_debug:
        class: Drupal\Console\Command\Libraries\DebugCommand
        tags:
          - { name: console.command }
  module_update:
        class: Drupal\Console\Command\Module\UpdateCommand
        tags:
          - { name: console.command }
  module_uninstall:
        class: Drupal\Console\Command\Module\UninstallCommand
        tags:
          - { name: console.command }
  module_install:
        class: Drupal\Console\Command\Module\InstallCommand
        tags:
          - { name: console.command }
  module_download:
        class: Drupal\Console\Command\Module\DownloadCommand
        tags:
          - { name: console.command }
  module_debug:
        class: Drupal\Console\Command\Module\DebugCommand
        tags:
          - { name: console.command }
  site_new:
        class: Drupal\Console\Command\Site\NewCommand
        tags:
          - { name: console.command }
  node_access_rebuild:
        class: Drupal\Console\Command\Node\AccessRebuildCommand
        tags:
          - { name: console.command }
  router_debug:
        class: Drupal\Console\Command\Router\DebugCommand
        tags:
          - { name: console.command }
          