services:
#  redbean:
#    class: RedBeanPHP\R
  console.annotation_reader:
    class: Doctrine\Common\Annotations\AnnotationReader
  console.annotation_file_cache:
    class: Doctrine\Common\Annotations\FileCacheReader
    factory: [Drupal\Console\Annotations\CacheFactory, createFileCache]
    arguments: ['@console.annotation_reader', '@console.configuration_manager']
#  console.command_dependencies:
#    class: Drupal\Console\Command\CommandDependencies
#    arguments: ["@console.annotation_file_cache"]
  console.drupal_api:
    class: Drupal\Console\Utils\DrupalApi
    arguments: ['@app.root']
#  file_util:
#    class: Drupal\Console\Utils\File
#  translator:
#    class: Drupal\Console\Utils\Translator
#    arguments: ["@parser", "@filesystem"]
#  console.translator:
#    class: Drupal\Console\Utils\Translator
#  showfile:
#    class: Drupal\Console\Utils\ShowFile
#    arguments: ["@site", "@translator"]
#  shell_process:
#    class: Drupal\Console\Utils\ShellProcess
#    arguments: ["@site", '@config']
