services:
  console.database_client:
    class: Drupal\Console\Command\Database\ClientCommand
    tags:
      - { name: drupal.command }
  console.database_query:
    class: Drupal\Console\Command\Database\QueryCommand
    tags:
      - { name: drupal.command }
  console.database_connect:
    class: Drupal\Console\Command\Database\ConnectCommand
    tags:
      - { name: drupal.command }
  console.database_drop:
    class: Drupal\Console\Command\Database\DropCommand
    arguments: ['@database']
    tags:
      - { name: drupal.command }
  console.database_dump:
    class: Drupal\Console\Command\Database\DumpCommand
    arguments: ['@app.root', '@console.shell_process']
    tags:
      - { name: drupal.command }
  console.database_log_clear:
    class: Drupal\Console\Command\Database\LogClearCommand
    arguments: ['@database']
    tags:
      - { name: drupal.command }
  console.database_log_debug:
    class: Drupal\Console\Command\Database\LogDebugCommand
    arguments: ['@database', '@date.formatter', '@entity_type.manager', '@string_translation']
    tags:
      - { name: drupal.command }
  console.database_restore:
    class: Drupal\Console\Command\Database\RestoreCommand
    arguments: ['@app.root']
    tags:
      - { name: drupal.command }
  console.database_table_debug:
    class: Drupal\Console\Command\Database\TableDebugCommand
    arguments: ['@console.redbean', '@database']
    tags:
      - { name: drupal.command }
