services:
  console.container_debug:
    class: Drupal\Console\Command\Debug\ContainerCommand
    tags:
      - { name: drupal.command }
  console.event_debug:
    class: Drupal\Console\Command\Debug\EventCommand
    arguments: ['@event_dispatcher']
    tags:
      - { name: drupal.command }
  console.permission_debug:
    class: Drupal\Console\Command\Debug\PermissionCommand
    tags:
      - { name: drupal.command }
  console.plugin_debug:
    class: Drupal\Console\Command\Debug\PluginCommand
    tags:
      - { name: drupal.command }
  console.views_debug:
    class: Drupal\Console\Command\Debug\ViewsCommand
    arguments: ['@entity_type.manager']
    tags:
      - { name: drupal.command }
