services:
  console.generate_module:
    class: Drupal\Console\Command\Generate\ModuleCommand
    arguments: ['@console.module_generator', '@console.validator', '@app.root', '@console.string_converter', '@console.drupal_api', '@http_client', '@console.site']
    tags:
       - { name: console.command }
  console.generate_authentication_provider:
    class: Drupal\Console\Command\Generate\AuthenticationProviderCommand
    arguments: ['@console.extension_manager', '@console.authentication_provider_generator', '@console.string_converter']
    tags:
       - { name: console.command }
  console.generate_controller:
    class: Drupal\Console\Command\Generate\ControllerCommand
    arguments: ['@console.extension_manager', '@console.controller_generator', '@console.string_converter', '@console.validator', '@router.route_provider', '@console.chain_queue']
    tags:
       - { name: console.command }
  console.generate_breakpoint:
    class: Drupal\Console\Command\Generate\BreakPointCommand
    arguments: ['@console.breakpoint_generator', '@app.root', '@theme_handler', '@console.validator', '@console.string_converter']
    tags:
      - { name: console.command }
  console.generate_form_alter:
    class: Drupal\Console\Command\Generate\FormAlterCommand
    arguments: ['@console.extension_manager', '@console.form_alter_generator', '@console.string_converter', '@module_handler', '@plugin.manager.element_info', '@?profiler', '@app.root', '@console.chain_queue']
    tags:
       - { name: console.command }
  console.generate_event_subscriber:
    class: Drupal\Console\Command\Generate\EventSubscriberCommand
    arguments: ['@console.extension_manager', '@console.event_subscriber_generator', '@console.string_converter', '@event_dispatcher', '@console.chain_queue']
    tags:
       - { name: console.command }
